### ISSUE TITLE
[QUESTION] Commit and Error Handling

### ISSUE THREAD

**Issue by francoisauclair911** [mateusjunges/laravel-kafka#125]
Hi,
I am wondering how does the `autoCommit()` feature works with the message handler if it throws an error?
Given I have the following, if I run the command, the error is thrown alright, but if I restart the command I don't see the "failed" message being reprocessed.

I think I'm missing a piece of the puzzle here

Thank you!
 ```
 $consumer = Kafka::createConsumer([
            'test_topic',
        ], 'g2', env('AD_KAFKA_BROKERS'))
            ->withAutoCommit()
            ->withOption('compression.codec', env('AD_KAFKA_COMPRESSION_TYPE'))
            ->withSasl(new Sasl(
                username: env('AD_KAFKA_USERNAME'),
                password: env('AD_KAFKA_PASSWORD'),
                mechanisms:  env('AD_KAFKA_SASL_MECHANISM'),
                securityProtocol:  env('AD_KAFKA_SASL_SECURITY_PROTOCOL'),
            ))
            ->withHandler(function (\Junges\Kafka\Contracts\KafkaConsumerMessage $message) {
                throw new Exception();
            })
            ->build();
$consumer->consume();
```

**Comment by mateusjunges** [comment]
Hi @francoisauclair911 sorry for my late response, I'm switching jobs right now and due to that I'm having a really busy week. 

Answering your question: 

When `auto-commit` is enabled, Kafka will auto commit the messages in a specified time interval. If the message consumption fails, it will try to commit to DLQ (if you have it enabled). Otherwise, the message will be commited as if it was successfully consumed.

You can check the `executeMessage` method: It runs a try catch block and if no execptions occur than the message is committed as successfully consumed (line 184). Then, if  any exception got caught, the consumer will try to handle the exception and then commit the message. 

https://github.com/mateusjunges/laravel-kafka/blob/a1be6819626236a1d81be3d7e335c7df0ec21b87/src/Consumers/Consumer.php#L177-L190

If `success` is equals to false, then the `commit` method will try to commit the message to the DLQ: 
https://github.com/mateusjunges/laravel-kafka/blob/a1be6819626236a1d81be3d7e335c7df0ec21b87/src/Consumers/Consumer.php#L304-L307

If no DLQ is configured, then the message will be committed using the default committer:
https://github.com/mateusjunges/laravel-kafka/blob/a1be6819626236a1d81be3d7e335c7df0ec21b87/src/Consumers/Consumer.php#L311

I hope it helps.

**Comment by mateusjunges** [comment]
I'm closing this due to lack of updates. Feel free to reopen or create a new issue if I have not answered your question.

**Comment by francoisauclair911** [comment]
Hi @mateusjunges  thanks for the reply. 

I'm new to Kafka so pardon my ignorance. My understanding would be that the messages would stay in the topic stream as long as they haven't be acknowledge by the consumer. But from what you are telling me if the consumer is down for a period of time it will still get the messages when back online but only if he fails to process them (via throwing error) then they will be pushed to a DLQ.

Am I getting this right 😄  ?
