### ISSUE TITLE
[BUG] Exception handling

### ISSUE THREAD

**Issue by behzadev** [mateusjunges/laravel-kafka#163]
**Describe the bug**
On throwing custom exceptions, the `report()` method of the exception is not called.

**To Reproduce**
1- Have a fresh Larvel installation.
2- Make a custom exception using `php artisan make:exception TestException`, then do something in your `report()` method of the exception, for example, `Log::info('some info')`. 
3- Create a consumer, then within the `handler()` of the consumer, throw the TestException.

**Expected behavior**
By default, if a custom exception is thrown in Laravel, if it has a `report()` method, it's gonna get called. this works just fine outside of the consumer `handle()` method, and the `report()` method gets called.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - mateusjunges/laravel-kafka v1.10
 - PHP 8.1

**Comment by mateusjunges** [comment]
Hey @behzadev thanks for reporting.

This happens because when a exception occurs within a consumer it is handled by the `handleException` method, on the base `Consumer` class, and this exception is never handled by Laravel's `Handler` class, which is reponsible for [calling the `report` method when it's present.
](https://laravel.com/docs/9.x/errors#renderable-exceptions)
https://github.com/mateusjunges/laravel-kafka/blob/bccc372fc85a72e8c9535382a095f312b4d6706d/src/Consumers/Consumer.php#L260-L277

And it only logs a message in the console:

![image](https://user-images.githubusercontent.com/19756164/210566451-470927f9-b585-4ee2-99d9-ed02aad9b9e0.png)

I'll add the laravel `reportable` concept for exception handling as soon as I have the time to work on it :slightly_smiling_face:

**Comment by behzadev** [comment]
Thanks for your reply

Is it also possible to discard committing the message if an exception is thrown?

**Comment by behzadev** [comment]
#168 solves this
