### ISSUE TITLE
[QUESTION] CouldNotPublishMessage exception: Sent messages may not be completed yet.

### ISSUE THREAD

**Issue by maquib** [mateusjunges/laravel-kafka#47]
@mateusjunges  can you plz help me on this error is coming when am trying to send message to kafka.
Here is my code,
![Screenshot (91)](https://user-images.githubusercontent.com/35573646/145770525-0c15efcc-4ab4-4b36-a2de-628d7ca819d9.png)
```php
Kafka::publishOn('broker', 'topic')
    ->withBodyKey('foo', 'bar')
    ->send();

return response('ok');
```

**Comment by mateusjunges** [comment]
Hey @maquib which `laravel-kafka` version are you using? The `publishOn('broker', 'topic')` was changed to `publishOn('topic', 'broker')`, with borker being optional in `v1.3.0`, so, if you are using the package with verision higher than `v1.3.0` it's trying to connect to `test_topic:9092`, which does not exist and is throwing this exception since kafka can't flush messages.

**Comment by maquib** [comment]
@mateusjunges <html>
<body>


rdkafka support | enabled
-- | --
version | 5.0.2
build date | Dec 10 2021 12:21:56
librdkafka version (runtime) | 1.6.2
librdkafka version (build) | 1.6.2.255


</body>
</html>

**Comment by mateusjunges** [comment]
@maquib which `laravel-kafka` do you have installed?

**Comment by maquib** [comment]
@mateusjunges I just run this command composer require mateusjunges/laravel-kafka i don't know which version it is. I think laravel-kafka version is v1.5.1 and rdkafka version is 5.0.2 and librdkafka version is 1.6.2. If this version. If the information related to the version is wrong then tell me How we will know the version?

**Comment by mateusjunges** [comment]
Yeah if you didn't specified a version then you're using `v1.5.1`. 
Your problem here is that you are using `publishOn('broker', 'topic'), but the syntax for `v1.5.1` is `publishOn('topic', 'broker'). So kafka is trying to connect to a broker at `topic:9092`, which does not exist, and gives you the mentioned exception.

The followint code should work fine:

```php
Kafka::publishOn('topic', 'broker')
    ->withBodyKey('foo', 'bar')
    ->send();

return response('ok');
```

Let me know if it helps.

**Comment by maquib** [comment]
@mateusjunges When we are sending message by the producer in the terminal, it is also recieving by the consumer in the terminal. But what is the problem in my code, again same error is coming which was coming before
![photo](https://user-images.githubusercontent.com/35573646/145953784-2e328585-ba21-43ca-b1e9-f9b51c10bcff.png)
![Screen Shot 2021-12-14 at 12 50 54 PM](https://user-images.githubusercontent.com/35573646/145953799-4b4f6146-9795-4da5-913d-de97bd046d4f.png)

Kafka::publishOn('test-topic', 'broker')
            ->withBodyKey('foo', 'bar')
            ->send();

        return response('ok');

![Screenshot (91)](https://user-images.githubusercontent.com/35573646/145953971-662bb3ee-5d07-4384-a987-7af6720a8ae0.png)

**Comment by mateusjunges** [comment]
Hey @maquib are you using the code exactly as you posted or did you replaced `broker` with your broker ip, which is `localhost:9092`?

This is a working example:

```php
Kafka::publishOn('test-topic', 'localhost:9092')
    ->withBodyKey('foo', 'bar')
    ->send();
```

**Comment by maquib** [comment]
@mateusjunges thank you 
its working.
