### ISSUE TITLE
[QUESTION] Example Project

### ISSUE THREAD

**Issue by Ceater** [mateusjunges/laravel-kafka#64]
Hello, i wonder if someone can share their example project on how to use this project..

i tried to install on my own, but always got so many error, inside this project varible or else..

**Comment by mateusjunges** [comment]
Hey @Ceater let me know if [this repo](https://github.com/mateusjunges/laravel-kafka-example) helps you

**Comment by Ceater** [comment]
Hi @mateusjunges , your repo help a lot. Since this is my 1st time using laravel and kafka i don't know what to do with your project.

but i wonder, if you can guide me more from installing to using the kafka..

here is what I know.

1. How to use and run your project on cloud.
2. changing consumer and producer

and here is what i want to know more.

1. Is there any delay between consumer and producer? i tried to change the debug logging using string but when i call the producer, i wont consume immediately. So i had to restart serve, kafka, and re-tail the log. But after few mins i can use it. So i wonder if your C and P have delay if i change the script.
2. How to implement your project in clean laravel or running laravel project? i always got error that my rdkafka version is 6.0 and your project req version 4.0 or 5.0 so i have to ignore req to bypass that problem.
3. Even if i successfully install via compose, i get error from RDKafka like this

<img width="463" alt="Screen Shot 2022-01-09 at 17 19 35" src="https://user-images.githubusercontent.com/16059037/148678196-0e77e0da-af8e-46ea-adbe-6433235b8e33.png">

because i new to laravel, i don't know what to do with that kind of error. maybe i forget to put certain php file to certain place. or else. So i wonder if you have time to guide me on how to use it for begginer.

thx

**Comment by mateusjunges** [comment]
To be honest with you i can't really take time to help you to set up this package, but i can give you some hints:

1) As kafka is `async`, you cannot assume that there is no delay between the time when it was published and it being consumed. Kafka is often used for communication in microservices architecture, so one service do not expect a synchronous response from another. If you change the code of your consumer you must always restart it in order to the changes to take effect, and yes, there can be some time until it start consuming messages again, at least in my tests in local environments. 
1) To install this package in a fresh laravel installation you can simply follow the readme documentation for installation instructions. About the requirements of `ext-rdkafka` on version 5.0 and 4.0, it is because on the time i created this package, these were the only versions available and compatible. Ext-rdkafka 6.0 was released on `2022-01-07`, and i will add it as a supported version as soon as i have time available to do that. 
1) The exception you are getting: `No such configuration property: "key"` occurs because you just copied the readme code and tried to pusblish messages using it. The `key` on `->withConfigOptions(['key' => 'value'])` means the kafka configuration key you want to set using that method, so its just a generic example. You can find all available  kafka consumer/producer configuration options [here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

**Comment by Ceater** [comment]
after few tries, i manage to run your project by manually add your composer to new project compose and run composer install..
then everything run fine till now, thx.

your example project help a lot
