### ISSUE TITLE
[BUG] CONFWARN on consumer with auto.offset.reset

### ISSUE THREAD

**Issue by therealsqvad** [mateusjunges/laravel-kafka#75]
**Describe the bug**
CONFWARN occurs when starting $consumer->consume();

**To Reproduce**
1. Start consumer with option `auto.offset.reset` 
```php 
 $consumer = Kafka::createConsumer(['topic', 'topic2'], 'group1', $broker_addr)
            ->withOptions([
                'auto.offset.reset'                     => 'earliest'
            ])
            ->withHandler(function (ConsumedMessage $message) { })
            ->build();
 $consumer->consume();
```
2. We get the warning "Configuration property auto.offset.reset is a consumer property and will be ignored by this producer instance". But we did not launch a producer, only a consumer
3. We get the warning "Configuration property compression.codec is a producer property and will be ignored by this consumer instance". But we did not specify the option `compression.codec` 

Why is the option `compression.codec` passed to `getConsumerOptions` , which is relevant only for the producer
https://github.com/mateusjunges/laravel-kafka/blob/b11aa8fb78f009b95e915eead4b5c5aadb732117/src/Config/Config.php#L70

Why is a producer created when calling `consume()`?
https://github.com/mateusjunges/laravel-kafka/blob/b11aa8fb78f009b95e915eead4b5c5aadb732117/src/Consumers/Consumer.php#L78

**Expected behavior**
The consumer will start without errors or warnings.

**Additional context**
Logs:

```log
%4|1645017413.959|CONFWARN|rdkafka#consumer-1| [thrd:app]: Configuration property compression.codec is a producer property and will be ignored by this consumer instance
%4|1645017413.963|CONFWARN|rdkafka#producer-2| [thrd:app]: Configuration property auto.offset.reset is a consumer property and will be ignored by this producer instance
```

**Comment by mateusjunges** [comment]
Hey @therealsqvad, i've created a pr to fix some issues i found while reading this.

> Why is the option compression.codec passed to getConsumerOptions , which is relevant only for the producer

Since you passed the `compression.codec` via `withOptions` method, it is intended as a custom option, and it is passed to the consumer builder. The problem is that the consumer creates a new producer to send messages to the dead letter queue, and the producer was being created with the same config options. I added a filter to reject consumer options while creating a producer, and also to reject producer options while creating consumers.

Thanks for reporting.

**Comment by therealsqvad** [comment]
@mateusjunges Thank you
